val = input("Digite algo: ")
print("O tipo primitivo desse valor é: ", type(val))
print('Só tem espaços? ', val.isspace())
print('É um número? ', val.isnumeric())
print('É alfabetico? ', val.isalpha())
print('É alfanumérico? ', val.isalnum())
print('Está em maiúsculo? ', val.isupper())
print('Está em minúscula? ', val.islower())
print('Está capitalizado? ', val.istitle())